---
- name: Disable CDP
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Disable Cisco Discovery Protocol
      ios_config:
        diff_against: running
        lines:
          - no cdp run
