---
- name: Enable CDP
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Enable Cisco Discovery Protocol
      ios_config:
        diff_against: running
        lines:
          - cdp run
