- name: Test Inventory
  hosts: ios
  roles:
    - name: ansible-network.cisco_ios
      function: get_facts
      subset:
        - system
        - interfaces
        - bgp
        - vrf
        - cdp
        - lldp
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
    - name: Store facts
      set_fact:
        hello: world
        cacheable: yes
